# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BudMan2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod "RKPieChart"
  # Pods for BudMan2

  target 'BudMan2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BudMan2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
